extend_content_security_policy:
  type: list
  default: "script_src: https://unpkg.com/@debtcollective/"
header_categories:
  type: list
  default: ""
  list_type: category
  description:
    en: A list of categories to render below the header. Defaults to off.
show_hero:
  type: bool
  default: true
show_current_efforts:
  type: bool
  default: false
logo_href:
  type: string
  default: ""
