extend_content_security_policy:
  type: list
  default: "script_src: https://unpkg.com/@debtcollective/|script_src: https://cdn.jsdelivr.net/gh/GraemeFulton/blm-badge/blmbadge.min.js"
header_categories_visible:
  type: bool
  default: true
  description:
    en: "Show the sub header with categories or not"
header_categories:
  type: list
  default: ""
  list_type: category
  description:
    en: A list of categories to render below the header. Defaults to off.
header_categories_custom_links:
  type: list
  default: ""
  description:
    en: "A list of links to render alongside header categories with format: text,url"
header_imported:
  default: false
  description:
    en: "Show imported header instead built-in"
header_imported_returnurl:
  type: string
  default: "https://community.debtcollective.org"
  desription:
    en: "set the url used to redirect user after success login"
show_hero:
  type: bool
  default: true
  description:
    en: "Show message banner on community homepage"
show_current_efforts:
  type: bool
  default: false
  description:
    en: "make visible pinned topics over 'all categories' page"
show_sidebar:
  type: bool
  default: false
  description:
    en: "enable possibility to show sidebar navigation for large screens"
events_url:
  type: string
  default: "/calendar"
  desription:
    en: "which page the users will visit to known about the upcoming events?"
logo_href:
  type: string
  default: ""
  description:
    en: "Edit url which the logo should map to"
popup_enabled:
  type: bool
  default: false
  description:
    en: "Show small element on bottom right to display a given message"
popup_url:
  description:
    en: Define the URL that user will redirect to when click the popup (use full url from browser bar)
  type: string
  default: "https://community.debtcollective.org/t/user-experience-feedback-new-theme/4110"
