extend_content_security_policy:
  type: list
  default: "script_src: https://unpkg.com/@debtcollective/"
header_categories:
  type: list
  default: ""
  list_type: category
  description:
    en: A list of categories to render below the header. Defaults to off.
show_hero:
  type: bool
  default: true
show_current_efforts:
  type: bool
  default: false
logo_href:
  type: string
  default: ""
popup_url:
  description:
    en: Define the URL that user will redirect to when click the popup (use full url from browser bar)
  type: string
  default: "https://community.debtcollective.org/t/user-experience-feedback-new-theme/4110"
